name: Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Rodar script Python
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          pip install requests
          python scraper.py
          
      - name: Salvar resultados
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add data/deals.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza ofertas" && git push)
